export const SCREENS = [
    {
        name: 'booth1',
        label: 'Booth 1',
        lottie1: '',
        lottie2: '',
        image1: '',
        image2: '',
        video1: 'assets/overlays/booth1.webm',
        video2: '',
    },
    {
        name: 'booth2',
        label: 'Booth 2',
        lottie1: '',
        lottie2: '',
        image1: '',
        image2: '',
        video1: 'assets/overlays/booth2.webm',
        video2: '',
    },
    {
        name: 'booth3',
        label: 'Booth 3',
        lottie1: '',
        lottie2: '',
        image1: '',
        image2: '',
        video1: 'assets/overlays/booth3.webm',
        video2: '',
    },
    {
        name: 'booth4',
        label: 'Booth 4',
        lottie1: '',
        lottie2: '',
        image1: '',
        image2: '',
        video1: 'assets/overlays/booth4.webm',
        video2: '',
    }
];