export const SCREENS = [
    {
        name: 'booth1',
        label: 'Booth 1',
        lottie1: '',
        lottie2: '',
        image1: '',
        image2: '',
        video1: 'assets/overlays/booth1.webm',
        video2: '',
    },
    {
        name: 'booth2',
        label: 'Booth 2',
        lottie1: 'assets/overlays/overlay1.json',
        lottie2: 'assets/overlays/character1.json',
        image1: 'assets/overlays/demo.webp',
        image2: '',
        video1: '',
        video2: '',
    },
    {
        name: 'booth3',
        label: 'Booth 3',
        lottie1: '',
        lottie2: '',
        image1: '',
        image2: '',
        video1: 'assets/overlays/buzo_face.webm',
        video2: 'assets/overlays/buzo_face.webm',
    },
];